Feature/servis
SamsaAhuerma/Hair-salon-app pull request #10
Opened 2024-06-22 21:48 UTC by nicoxynos5

CRUD de servis

2024-06-24 18:37 UTC, RenzoSC requested changes
Dentro del modelo de servis debería haber un campo que indique el precio del servicio, cuando alguien quiera reservar un turno se le desplegarán las opciones de servicio para dicho turno, y junto con las opciones de servicio también deberían estar adjuntados los precios actualizados. Creo que el campo de precio es importante.

2024-06-24 18:37 UTC, RenzoSC commented on Backend/models/servis.py
¿No haría falta un campo donde indique el precio del servicio?

2024-06-26 15:21 UTC, nicoxynos5 commented on Backend/models/servis.py
Perfecto, lo agrego y mas adelante podriamos tener una funcion que tome un numero o porcentaje y se actualice el precio en base a eso.

2024-06-26 17:15 UTC, RenzoSC approved these changes

2024-06-26 17:15 UTC, merged